# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: Welecja # jekyll-seo-tag > Owners twitter username
author: Welecja # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Welecja # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    # - https://twitter.com/Welecja
    - https://www.facebook.com/Welecja1883
    - https://github.com/welecja
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Aktualności # Needed for Siteleaf
    output: true
    # description: "Aktualności Weleckie" # The post list page content
    # feature_text: |
    #   Welcome to the blog
    feature_image: "/assets/images/140lecie.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pl-PL # Set the site language
title: "Welecja" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/herb.png" # Site logo, also used in jekyll-seo-tag
description: "Korporacja Akademicka Welecja" # Site description and default description, also used in jekyll-seo-tag
url: "https://welecja.pl" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/welecja/"
email: "welecja@welecja.pl"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  32: '/assets/logos/favicon.png'

# 9. Site navigation
navigation_header:
- title: Wprowadzenie
  url: /
- title: Podstawy
  url: /podstawy/
- title: Aktualności
  url: /blog/
- title: Historia
  url: /historia/
- title: Korporacje
  url: /Korporacje/
- title: Kontakt
  url: /kontakt/
- title: Archiwum
  url: https://welecja.github.io/welecja-pre2023/welecja.pl/index.html
- title: Dla Weletów
  url: /dla-weletow/
  
# - title: Categories
#   url: /categories/
# - title: Search
#   url: /search/


navigation_footer:
- title:  Korporacja Akademicka Welecja
  url: https://welecja.pl

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  Facebook: https://www.facebook.com/welecja1883/
  # GitHub: https://github.com/daviddarnes
  # link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    -'https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,400;0,700;0,900;1,100;1,400;1,700;1,900&family=Limelight&display=swap

